# Generated by Django 3.2.9 on 2021-11-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import v1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(default='익명', max_length=8, unique=True)),
                ('profileImgURL', models.ImageField(default='v1/default/profile.jpg', null=True, upload_to='v1', verbose_name='profile Image')),
                ('region', models.CharField(blank=True, default='서울', max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', v1.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='artPost',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('title', models.CharField(blank=True, default='제목', max_length=40)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emailAuth',
            fields=[
                ('mail', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Mail Sender')),
                ('authCode', models.CharField(max_length=8, verbose_name='Auth')),
                ('requestTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='RequestedTime')),
                ('isAuthed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='marketPost',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('postKind', models.CharField(blank=True, default='sell', max_length=10)),
                ('trashKind', models.CharField(blank=True, default='기타', max_length=30)),
                ('content', models.TextField(blank=True, default='')),
                ('qty', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('role', models.CharField(blank=True, default='리사이클러', max_length=10)),
                ('kakaoID', models.CharField(blank=True, default='', max_length=50)),
                ('openChat', models.TextField(default='')),
                ('instagram', models.CharField(blank=True, default='', max_length=30)),
                ('about', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marketPostImage',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='v1')),
                ('postModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.marketpost')),
            ],
        ),
        migrations.CreateModel(
            name='garbage_output',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('date_year', models.IntegerField(blank=True)),
                ('date_month', models.IntegerField(blank=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='challengePostImage',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='v1')),
                ('postModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.artpost')),
            ],
        ),
        migrations.CreateModel(
            name='challengePost',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('title', models.CharField(blank=True, default='제목', max_length=40)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.artpost')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='artPostImage',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='v1')),
                ('postModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.artpost')),
            ],
        ),
    ]
