# Generated by Django 3.2.9 on 2021-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpostimage',
            name='order',
            field=models.IntegerField(blank=True, db_column='image_order', verbose_name='image_order'),
        ),
        migrations.AlterField(
            model_name='challengepostimage',
            name='order',
            field=models.IntegerField(blank=True, db_column='image_order', verbose_name='image_order'),
        ),
        migrations.AlterField(
            model_name='marketpostimage',
            name='order',
            field=models.IntegerField(blank=True, db_column='image_order', verbose_name='image_order'),
        ),
    ]
